# Generated by Django 2.2.28 on 2023-10-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Enter first name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Enter last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Enter Email')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
